
## Configure Theme Variables
POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k
POWERLEVEL9K_MODE='nerdfont-complete'

## Configure Prompt Colors
POWERLEVEL9K_DIR_HOME_FOREGROUND='233'
POWERLEVEL9K_DIR_HOME_BACKGROUND='214'

POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='233'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='214'

POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='233'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='214'

POWERLEVEL9K_VCS_CLEAN_FOREGROUND='063'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='233'

POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='197'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='233'

POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='197'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='233'

## Configure Prompt Variables
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_SHORTEN_DELIMITER=''
POWERLEVEL9K_SHORTEN_DIR_LENGTH='1'

POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S}"
POWERLEVEL9K_TIME_BACKGROUND="233"
POWERLEVEL9K_TIME_FOREGROUND="010"

## Configure Prompt Sections
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
